services:
  care-admin:
    build:
      context: .
    image: care/care-admin:uat
    container_name: care-admin
    env_file:
      - /opt/wecare/secrets/care-admin-object-storage.env
    mem_limit: 1g
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: uat
      TZ: Asia/Colombo
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx768m -Duser.timezone=Asia/Colombo"
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/caresystem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
