package com.dtech.admin.enums;

public enum ClaimEmailEvent {
    CLAIM_L1_APPROVED,
    CLAIM_L1_REJECTED,
    CLAIM_L2_MATCHED_APPROVAL,
    CLAIM_L2_DIFFERENT_DECISION,
    CLAIM_L2_REJECTED_AFTER_L1_APPROVED,
    CLAIM_L2_REJECTED_AFTER_L1_REJECTED,
    CLAIM_L3_FINAL_DECISION
}
