package com.dtech.admin.enums;

public enum MessageType {
 USER_CREATION,SENT_OTP_PASSWORD,INSURANCE_APPROVAL,INSURANCE_REJECTED,DEATH_REJECTED,DEATH_APPROVAL,CIVIL_STATUS_REJECTED,DEPENDENT_REJECTED,CIVIL_STATUS_APPROVED,DEPENDENT_APPROVED
}

