package com.dtech.admin.enums;

public enum WebTask {
    LOGIN,SEARCH,FILTER_LIST,REF_DATA,UPDATE,VIEW,DELETE,DEACTIVATE,ADD,PASSWORD_RESET,SENT_OTP_PASSWORD,FILE_UPLOAD,FILE_DOWNLOAD,
    STAFF_CAT_UPDATE,STAFF_CAT_TRANSFER
}
